### ISSUE TITLE
文件打开错误

### ISSUE THREAD

**Issue by liwenwei5110** [jinweiluo/BERT4Rec_AC#2]
我运行gen_data_ml1m.py脚本到555行时 f = open(output_dir + dataset_name + "_train_" + str(i) + ".txt") 这里时出错了，之前没有产生过这个文件，这里打开会报错，请问这是什么问题

**Comment by jinweiluo** [comment]
Hi, 我刚刚将项目下载到我的电脑重新运行了gen_data_ml1m.py 没有报错 
你可以确认一下有没有修改文件生成的路径 
代码会在bert_train/data 生成ml1m_train_1.txt, xx_2.txt等等 最后再将这些合并得到最终的训练集

**Comment by liwenwei5110** [comment]
> 
没有修改，生成 ml1m_train_1.txt, xx_2.txt 这些文件是在555行这里生成的吗，还是之前就生成的。
其实我主要是想看一下它的负采样是怎么做的，不清楚怎么做流行度负采样，请问你方便跟我说一下吗，谢谢了！

**Comment by jinweiluo** [comment]
555行之前生成的 你可以看一下代码中的226，252行。
至于流行度负采样，你可以看看这个项目中candidate_gen.py
另外，BERT4Rec作者源码中也有对应的处理代码。没记错的话我是根据他的源码写的。
希望能帮到你。

**Comment by liwenwei5110** [comment]
> 555行之前生成的 你可以看一下代码中的226，252行。 至于流行度负采样，你可以看看这个项目中candidate_gen.py 另外，BERT4Rec作者源码中也有对应的处理代码。没记错的话我是根据他的源码写的。 希望能帮到你。

谢谢
